#!/bin/bash

basedir=`dirname $0`/mongodb
dbpath=$basedir/var/data/mongodb
logpath=$basedir/var/log/mongodb.log
conf=$basedir/etc/mongodb.conf
mongo_opts="-f $conf --dbpath $dbpath --logpath=$logpath"
mongo_ver=2.0.1

if [ ! -d "$dbpath" ]; then
     mkdir -p $dbpath
fi

if [ ! -d `dirname $logpath` ]; then
     mkdir -p `dirname $logpath`
fi

if [ `uname` == 'Darwin' ]; then
    mongodcmd=$basedir/mongodb-osx-x86_64-$mongo_ver/bin/mongod
    mongocmd=$basedir/mongodb-osx-x86_64-$mongo_ver/bin/mongo
fi

case $1 in
  start)
    $mongodcmd $mongo_opts
  ;;
  stop)
    $mongocmd --quiet --eval 'db.shutdownServer()' admin
  ;;
  status)
    tail -n 20 $logpath
  ;;
  *)
    echo "$0 (status|start|stop)"
  ;;
esac
